name: Build Manager (ARM64 No Sign)

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/build-manager.yml'
      - 'repack_apk.py'
      - 'manager/**'
      - 'kernel/**'
      - 'userspace/**'

  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/build-manager.yml'
      - 'repack_apk.py'
      - 'manager/**'
      - 'kernel/**'
      - 'userspace/**'

  workflow_dispatch:

jobs:

  build-lkm:
    uses: ./.github/workflows/build-lkm.yml
    secrets: inherit

  build-ksuinit:
    uses: ./.github/workflows/ksuinit.yml

  build-ksud:
    needs: [build-lkm, build-ksuinit]
    uses: ./.github/workflows/ksud.yml
    with:
      target: aarch64-linux-android
      pack_lkm: true
      pack_ksuinit: true

  build-manager:
    needs: [build-lkm]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./manager

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Spoof Package ID
        run: |
          chmod +x spoof
          ./spoof

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4

      - name: Build APK (UNSIGNED)
        run: ./gradlew clean assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: manager-arm64
          path: manager/app/build/outputs/apk/release/*.apk
